# Generated by Django 3.2.8 on 2021-10-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
                ('specialItemId', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MostPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('pickDate', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApiApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('menuName', models.CharField(max_length=100)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodApiApp.food')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('paymentType', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApiApp.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApiApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodId', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=100)),
                ('administator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApiApp.administator')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApiApp.menu'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodApiApp.food')),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodApiApp.order')),
            ],
        ),
    ]
